// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"code.byted.org/gopkg/thrift"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	"toutiao/videoarch/video_data_access"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  CreateVideoInfoResponse CreateVideoInfo(CreateVideoInfoRequest req)")
	fmt.Fprintln(os.Stderr, "  UpdateVideoInfoResponse UpdateVideoInfo(UpdateVideoInfoRequest req)")
	fmt.Fprintln(os.Stderr, "  CreateUploadRecordResponse CreateUploadRecord(CreateUploadRecordRequest req)")
	fmt.Fprintln(os.Stderr, "  UpdateUploadRecordResponse UpdateUploadRecord(UpdateUploadRecordRequest req)")
	fmt.Fprintln(os.Stderr, "  CreateEncodedVideoInfoResponse CreateEncodedVideoInfo(CreateEncodedVideoInfoRequest req)")
	fmt.Fprintln(os.Stderr, "  MGetVideoInfoResponse MGetVideoInfo(MGetVideoInfoRequest req)")
	fmt.Fprintln(os.Stderr, "  MRefreshVideoInfoResponse MRefreshVideoInfo(MRefreshVideoInfoRequest req)")
	fmt.Fprintln(os.Stderr, "  GetProviderInfoResponse GetProviderInfo(GetProviderInfoRequest req)")
	fmt.Fprintln(os.Stderr, "  GetProviderInfoByUserKeyResponse GetProviderInfoByUserKey(GetProviderInfoByUserKeyRequest req)")
	fmt.Fprintln(os.Stderr, "  CreatePosterCandidatesResponse CreatePosterCandidates(CreatePosterCandidatesRequest req)")
	fmt.Fprintln(os.Stderr, "  MGetPosterCandidatesResponse MGetPosterCandidates(MGetPosterCandidatesRequest req)")
	fmt.Fprintln(os.Stderr, "  UpdateVideoExtraResponse UpdateVideoExtra(UpdateVideoExtraRequest req)")
	fmt.Fprintln(os.Stderr, "  MUpdateVideoExtraResponse MUpdateVideoExtra(MUpdateVideoExtraRequest req)")
	fmt.Fprintln(os.Stderr, "  MGetVideoPlayStatusResponse MGetVideoPlayStatus(MGetVideoPlayStatusRequest req)")
	fmt.Fprintln(os.Stderr, "  UpdateVideoPlayStatusResponse UpdateVideoPlayStatus(UpdateVideoPlayStatusRequest req)")
	fmt.Fprintln(os.Stderr, "  UpdateEncodedTypeResponse UpdateEncodedType(UpdateEncodedTypeRequest req)")
	fmt.Fprintln(os.Stderr, "  CreateDynamicLogoInfoResponse CreateDynamicLogoInfo(CreateDynamicLogoInfoRequest req)")
	fmt.Fprintln(os.Stderr, "  GetDynamicLogoInfoResponse GetDynamicLogoInfo(GetDynamicLogoInfoRequest req)")
	fmt.Fprintln(os.Stderr, "  GetVideoStoreInfosByMD5Response GetVideoStoreInfosByMD5(GetVideoStoreInfosByMD5Request req)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := video_data_access.NewVideoDataAccessServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "CreateVideoInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateVideoInfo requires 1 args")
			flag.Usage()
		}
		arg61 := flag.Arg(1)
		mbTrans62 := thrift.NewTMemoryBufferLen(len(arg61))
		defer mbTrans62.Close()
		_, err63 := mbTrans62.WriteString(arg61)
		if err63 != nil {
			Usage()
			return
		}
		factory64 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt65 := factory64.GetProtocol(mbTrans62)
		argvalue0 := video_data_access.NewCreateVideoInfoRequest()
		err66 := argvalue0.Read(jsProt65)
		if err66 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateVideoInfo(value0))
		fmt.Print("\n")
		break
	case "UpdateVideoInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateVideoInfo requires 1 args")
			flag.Usage()
		}
		arg67 := flag.Arg(1)
		mbTrans68 := thrift.NewTMemoryBufferLen(len(arg67))
		defer mbTrans68.Close()
		_, err69 := mbTrans68.WriteString(arg67)
		if err69 != nil {
			Usage()
			return
		}
		factory70 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt71 := factory70.GetProtocol(mbTrans68)
		argvalue0 := video_data_access.NewUpdateVideoInfoRequest()
		err72 := argvalue0.Read(jsProt71)
		if err72 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateVideoInfo(value0))
		fmt.Print("\n")
		break
	case "CreateUploadRecord":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateUploadRecord requires 1 args")
			flag.Usage()
		}
		arg73 := flag.Arg(1)
		mbTrans74 := thrift.NewTMemoryBufferLen(len(arg73))
		defer mbTrans74.Close()
		_, err75 := mbTrans74.WriteString(arg73)
		if err75 != nil {
			Usage()
			return
		}
		factory76 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt77 := factory76.GetProtocol(mbTrans74)
		argvalue0 := video_data_access.NewCreateUploadRecordRequest()
		err78 := argvalue0.Read(jsProt77)
		if err78 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateUploadRecord(value0))
		fmt.Print("\n")
		break
	case "UpdateUploadRecord":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateUploadRecord requires 1 args")
			flag.Usage()
		}
		arg79 := flag.Arg(1)
		mbTrans80 := thrift.NewTMemoryBufferLen(len(arg79))
		defer mbTrans80.Close()
		_, err81 := mbTrans80.WriteString(arg79)
		if err81 != nil {
			Usage()
			return
		}
		factory82 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt83 := factory82.GetProtocol(mbTrans80)
		argvalue0 := video_data_access.NewUpdateUploadRecordRequest()
		err84 := argvalue0.Read(jsProt83)
		if err84 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateUploadRecord(value0))
		fmt.Print("\n")
		break
	case "CreateEncodedVideoInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateEncodedVideoInfo requires 1 args")
			flag.Usage()
		}
		arg85 := flag.Arg(1)
		mbTrans86 := thrift.NewTMemoryBufferLen(len(arg85))
		defer mbTrans86.Close()
		_, err87 := mbTrans86.WriteString(arg85)
		if err87 != nil {
			Usage()
			return
		}
		factory88 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt89 := factory88.GetProtocol(mbTrans86)
		argvalue0 := video_data_access.NewCreateEncodedVideoInfoRequest()
		err90 := argvalue0.Read(jsProt89)
		if err90 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateEncodedVideoInfo(value0))
		fmt.Print("\n")
		break
	case "MGetVideoInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "MGetVideoInfo requires 1 args")
			flag.Usage()
		}
		arg91 := flag.Arg(1)
		mbTrans92 := thrift.NewTMemoryBufferLen(len(arg91))
		defer mbTrans92.Close()
		_, err93 := mbTrans92.WriteString(arg91)
		if err93 != nil {
			Usage()
			return
		}
		factory94 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt95 := factory94.GetProtocol(mbTrans92)
		argvalue0 := video_data_access.NewMGetVideoInfoRequest()
		err96 := argvalue0.Read(jsProt95)
		if err96 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.MGetVideoInfo(value0))
		fmt.Print("\n")
		break
	case "MRefreshVideoInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "MRefreshVideoInfo requires 1 args")
			flag.Usage()
		}
		arg97 := flag.Arg(1)
		mbTrans98 := thrift.NewTMemoryBufferLen(len(arg97))
		defer mbTrans98.Close()
		_, err99 := mbTrans98.WriteString(arg97)
		if err99 != nil {
			Usage()
			return
		}
		factory100 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt101 := factory100.GetProtocol(mbTrans98)
		argvalue0 := video_data_access.NewMRefreshVideoInfoRequest()
		err102 := argvalue0.Read(jsProt101)
		if err102 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.MRefreshVideoInfo(value0))
		fmt.Print("\n")
		break
	case "GetProviderInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetProviderInfo requires 1 args")
			flag.Usage()
		}
		arg103 := flag.Arg(1)
		mbTrans104 := thrift.NewTMemoryBufferLen(len(arg103))
		defer mbTrans104.Close()
		_, err105 := mbTrans104.WriteString(arg103)
		if err105 != nil {
			Usage()
			return
		}
		factory106 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt107 := factory106.GetProtocol(mbTrans104)
		argvalue0 := video_data_access.NewGetProviderInfoRequest()
		err108 := argvalue0.Read(jsProt107)
		if err108 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetProviderInfo(value0))
		fmt.Print("\n")
		break
	case "GetProviderInfoByUserKey":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetProviderInfoByUserKey requires 1 args")
			flag.Usage()
		}
		arg109 := flag.Arg(1)
		mbTrans110 := thrift.NewTMemoryBufferLen(len(arg109))
		defer mbTrans110.Close()
		_, err111 := mbTrans110.WriteString(arg109)
		if err111 != nil {
			Usage()
			return
		}
		factory112 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt113 := factory112.GetProtocol(mbTrans110)
		argvalue0 := video_data_access.NewGetProviderInfoByUserKeyRequest()
		err114 := argvalue0.Read(jsProt113)
		if err114 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetProviderInfoByUserKey(value0))
		fmt.Print("\n")
		break
	case "CreatePosterCandidates":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CreatePosterCandidates requires 1 args")
			flag.Usage()
		}
		arg115 := flag.Arg(1)
		mbTrans116 := thrift.NewTMemoryBufferLen(len(arg115))
		defer mbTrans116.Close()
		_, err117 := mbTrans116.WriteString(arg115)
		if err117 != nil {
			Usage()
			return
		}
		factory118 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt119 := factory118.GetProtocol(mbTrans116)
		argvalue0 := video_data_access.NewCreatePosterCandidatesRequest()
		err120 := argvalue0.Read(jsProt119)
		if err120 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreatePosterCandidates(value0))
		fmt.Print("\n")
		break
	case "MGetPosterCandidates":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "MGetPosterCandidates requires 1 args")
			flag.Usage()
		}
		arg121 := flag.Arg(1)
		mbTrans122 := thrift.NewTMemoryBufferLen(len(arg121))
		defer mbTrans122.Close()
		_, err123 := mbTrans122.WriteString(arg121)
		if err123 != nil {
			Usage()
			return
		}
		factory124 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt125 := factory124.GetProtocol(mbTrans122)
		argvalue0 := video_data_access.NewMGetPosterCandidatesRequest()
		err126 := argvalue0.Read(jsProt125)
		if err126 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.MGetPosterCandidates(value0))
		fmt.Print("\n")
		break
	case "UpdateVideoExtra":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateVideoExtra requires 1 args")
			flag.Usage()
		}
		arg127 := flag.Arg(1)
		mbTrans128 := thrift.NewTMemoryBufferLen(len(arg127))
		defer mbTrans128.Close()
		_, err129 := mbTrans128.WriteString(arg127)
		if err129 != nil {
			Usage()
			return
		}
		factory130 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt131 := factory130.GetProtocol(mbTrans128)
		argvalue0 := video_data_access.NewUpdateVideoExtraRequest()
		err132 := argvalue0.Read(jsProt131)
		if err132 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateVideoExtra(value0))
		fmt.Print("\n")
		break
	case "MUpdateVideoExtra":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "MUpdateVideoExtra requires 1 args")
			flag.Usage()
		}
		arg133 := flag.Arg(1)
		mbTrans134 := thrift.NewTMemoryBufferLen(len(arg133))
		defer mbTrans134.Close()
		_, err135 := mbTrans134.WriteString(arg133)
		if err135 != nil {
			Usage()
			return
		}
		factory136 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt137 := factory136.GetProtocol(mbTrans134)
		argvalue0 := video_data_access.NewMUpdateVideoExtraRequest()
		err138 := argvalue0.Read(jsProt137)
		if err138 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.MUpdateVideoExtra(value0))
		fmt.Print("\n")
		break
	case "MGetVideoPlayStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "MGetVideoPlayStatus requires 1 args")
			flag.Usage()
		}
		arg139 := flag.Arg(1)
		mbTrans140 := thrift.NewTMemoryBufferLen(len(arg139))
		defer mbTrans140.Close()
		_, err141 := mbTrans140.WriteString(arg139)
		if err141 != nil {
			Usage()
			return
		}
		factory142 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt143 := factory142.GetProtocol(mbTrans140)
		argvalue0 := video_data_access.NewMGetVideoPlayStatusRequest()
		err144 := argvalue0.Read(jsProt143)
		if err144 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.MGetVideoPlayStatus(value0))
		fmt.Print("\n")
		break
	case "UpdateVideoPlayStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateVideoPlayStatus requires 1 args")
			flag.Usage()
		}
		arg145 := flag.Arg(1)
		mbTrans146 := thrift.NewTMemoryBufferLen(len(arg145))
		defer mbTrans146.Close()
		_, err147 := mbTrans146.WriteString(arg145)
		if err147 != nil {
			Usage()
			return
		}
		factory148 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt149 := factory148.GetProtocol(mbTrans146)
		argvalue0 := video_data_access.NewUpdateVideoPlayStatusRequest()
		err150 := argvalue0.Read(jsProt149)
		if err150 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateVideoPlayStatus(value0))
		fmt.Print("\n")
		break
	case "UpdateEncodedType":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateEncodedType requires 1 args")
			flag.Usage()
		}
		arg151 := flag.Arg(1)
		mbTrans152 := thrift.NewTMemoryBufferLen(len(arg151))
		defer mbTrans152.Close()
		_, err153 := mbTrans152.WriteString(arg151)
		if err153 != nil {
			Usage()
			return
		}
		factory154 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt155 := factory154.GetProtocol(mbTrans152)
		argvalue0 := video_data_access.NewUpdateEncodedTypeRequest()
		err156 := argvalue0.Read(jsProt155)
		if err156 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateEncodedType(value0))
		fmt.Print("\n")
		break
	case "CreateDynamicLogoInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateDynamicLogoInfo requires 1 args")
			flag.Usage()
		}
		arg157 := flag.Arg(1)
		mbTrans158 := thrift.NewTMemoryBufferLen(len(arg157))
		defer mbTrans158.Close()
		_, err159 := mbTrans158.WriteString(arg157)
		if err159 != nil {
			Usage()
			return
		}
		factory160 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt161 := factory160.GetProtocol(mbTrans158)
		argvalue0 := video_data_access.NewCreateDynamicLogoInfoRequest()
		err162 := argvalue0.Read(jsProt161)
		if err162 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateDynamicLogoInfo(value0))
		fmt.Print("\n")
		break
	case "GetDynamicLogoInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDynamicLogoInfo requires 1 args")
			flag.Usage()
		}
		arg163 := flag.Arg(1)
		mbTrans164 := thrift.NewTMemoryBufferLen(len(arg163))
		defer mbTrans164.Close()
		_, err165 := mbTrans164.WriteString(arg163)
		if err165 != nil {
			Usage()
			return
		}
		factory166 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt167 := factory166.GetProtocol(mbTrans164)
		argvalue0 := video_data_access.NewGetDynamicLogoInfoRequest()
		err168 := argvalue0.Read(jsProt167)
		if err168 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetDynamicLogoInfo(value0))
		fmt.Print("\n")
		break
	case "GetVideoStoreInfosByMD5":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetVideoStoreInfosByMD5 requires 1 args")
			flag.Usage()
		}
		arg169 := flag.Arg(1)
		mbTrans170 := thrift.NewTMemoryBufferLen(len(arg169))
		defer mbTrans170.Close()
		_, err171 := mbTrans170.WriteString(arg169)
		if err171 != nil {
			Usage()
			return
		}
		factory172 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt173 := factory172.GetProtocol(mbTrans170)
		argvalue0 := video_data_access.NewGetVideoStoreInfosByMD5Request()
		err174 := argvalue0.Read(jsProt173)
		if err174 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetVideoStoreInfosByMD5(value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
