// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package video_data_access

import (
	"bytes"
	"code.byted.org/gopkg/thrift"
	"code.byted.org/videoarch/transcoder/thrift_gen/base"
	"code.byted.org/videoarch/transcoder/thrift_gen/videoarch_common"
	"fmt"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = base.GoUnusedProtection__
var _ = videoarch_common.GoUnusedProtection__

func init() {
}
